Repository ucsb-cs156-s25/proj-courses-s25-05, pull requests merged in 2025-05, with the labels that each got.

#22 Created a placeholder GESearchPage
  frontend/src/App.js
  frontend/src/fixtures/geSearchFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/GeneralEducation/GeneralEducationSearchPage.js
  frontend/src/stories/pages/GeneralEducation/GeneralEducationSearchPage.stories.js
  frontend/src/tests/pages/GeneralEducation/GeneralEducationSearchPage.test.js
Labels: 10

#25 SingleAreaDropdown for GeneralEducationSearch complete
  frontend/src/fixtures/areaFixtures.js
  frontend/src/main/components/Areas/SingleAreaDropdown.js
  frontend/src/stories/components/Areas/SingleAreaDropdown.stories.js
  frontend/src/tests/components/Areas/SingleAreaDropdown.test.js
Labels: 10

#31 Paginated Jobs Backend Endpoint
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/JobsRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
Labels: 10, Merge Candidate-CI

#28 Created a dropdown for classroom numbers
  frontend/.eslintignore
  frontend/src/fixtures/classroomFixtures.js
  frontend/src/main/components/Classrooms/SingleClassroomDropdown.js
  frontend/src/stories/components/Classrooms/SingleClassroomDropdown.stories.js
  frontend/src/tests/components/Classrooms/SingleClassroomDropdown.test.js
Labels: 10, Merge Candidate-CI

#29 Added a new endpoint for searching by building code and room number
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseBuildingRoomController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseBuildingRoomControllerTests.java
Labels: 10, Merge Candidate-CI

#34 GE Area Search Form Component
  frontend/src/fixtures/geSearchFixtures.js
  frontend/src/main/components/GeneralEducation/GeneralEducationSearchForm.js
  frontend/src/stories/components/GeneralEducation/GeneralEducationSearchForm.stories.js
  frontend/src/tests/components/GeneralEducation/GeneralEducationSearchForm.test.js
Labels: 10, Merge Candidate-CI

#26 GE List API
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate-CI

#35 Weekly View for Personal Schedules
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/fixtures/personalSectionsEventsFixtures.js
  frontend/src/main/components/PersonalSchedulesWeeklyView/PersonalSchedulesWeeklyViewEvent.js
  frontend/src/main/components/PersonalSchedulesWeeklyView/PersonalSchedulesWeeklyViewPanel.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/stories/pages/PersonalSchedules/PersonalSchedulesDetailsPage.stories.js
  frontend/src/tests/components/PersonalSchedulesWeeklyView/PersonalSchedulesWeeklyViewEvent.test.js
  frontend/src/tests/components/PersonalSchedulesWeeklyView/PersonalSchedulesWeeklyViewPanel.test.js
Labels: 20, Merge Candidate-CI
